### ISSUE TITLE
React Warning; unknown props on div

### ISSUE THREAD

**Issue by JaccoGoris** [javierbyte/react-blur#15]
Hi, I'm getting the following warning when using this component:

`Warning: Unknown props blurRadius, img, resizeInterval, onLoadFunction on <div> tag. Remove these props from the element`

Due to the spread operator in the final div. Is there anything I can do on my end to avoid this error? thanks!

**Comment by javierbyte** [comment]
Hi @JaccoGoris, @mherodev already solved this issue :)
