### ISSUE TITLE
componentWillReceiveProps should not re-blur image unless props changed

### ISSUE THREAD

**Issue by mull** [javierbyte/react-blur#5]
Hi javierbyte,

```js
    componentWillReceiveProps(nextProps) {
        stackBlurImage(this.img, this.canvas, nextProps.blurRadius, this.width, this.height);
    },
```

This is quite a waste, as you don't check if the props actually change. Perhaps this should be done in `componentWillUpdate` - or just check if the props changed?

**Comment by javierbyte** [comment]
You are right!
I will fix this tonight.
Thank you!

**Comment by javierbyte** [comment]
Done!
